import type {
  Agent, Task, Message, Workflow, Resource, BudgetAllocation,
  KPIMetric, ActivityEvent, Alert, Simulation, ApprovalRequest,
  KanoseiNotification, AgentLoad, PipelineStage, MessageFlow, KanoseiWorkflow,
} from './types'

export const AGENTS: Agent[] = [
  {
    id: 'ceo',
    name: 'CEO',
    role: 'Chief Executive Officer',
    status: 'active',
    hierarchyLevel: 1,
    trustLevel: 100,
    specialization: 'Strategic leadership, company-wide decision making, executive approvals',
    autonomousActions: ['Approve budgets >$50K', 'Set quarterly priorities', 'Resolve cross-department conflicts', 'Hire/fire executives'],
    decisionCriteria: ['Revenue impact', 'Strategic alignment', 'Risk assessment', 'Resource availability'],
    tools: ['Budget dashboard', 'Performance metrics', 'Board reporting', 'Strategic planner'],
    escalationRules: ['Board notification for >$500K decisions', 'Emergency protocol for system failures'],
    communicationStyle: 'Directive, concise, outcome-focused',
    activeTaskCount: 3,
    completedTasks: 142,
    successRate: 94,
    totalMessages: 389,
    resourceUsage: 45,
    color: '#f59e0b',
    gradient: 'from-amber-500/20 to-orange-500/10',
  },
  {
    id: 'product',
    name: 'Product',
    role: 'Product Manager',
    status: 'busy',
    hierarchyLevel: 2,
    trustLevel: 85,
    specialization: 'Product strategy, backlog prioritization, feature planning, user research',
    autonomousActions: ['Prioritize backlog', 'Write PRDs', 'Run user interviews', 'Define acceptance criteria'],
    decisionCriteria: ['Impact/effort ratio', 'User feedback', 'Business value', 'Technical feasibility'],
    tools: ['Backlog manager', 'Roadmap planner', 'Analytics dashboard', 'User feedback aggregator'],
    escalationRules: ['CEO approval for roadmap pivots', 'Engineering sign-off for scope changes'],
    communicationStyle: 'Collaborative, data-driven, user-centric',
    activeTaskCount: 7,
    completedTasks: 98,
    successRate: 87,
    totalMessages: 256,
    resourceUsage: 78,
    color: '#8b5cf6',
    gradient: 'from-violet-500/20 to-purple-500/10',
  },
  {
    id: 'engineering',
    name: 'Engineering',
    role: 'Engineering Lead',
    status: 'busy',
    hierarchyLevel: 2,
    trustLevel: 88,
    specialization: 'System architecture, code review, technical execution, infrastructure',
    autonomousActions: ['Architect systems', 'Review code', 'Deploy services', 'Manage CI/CD'],
    decisionCriteria: ['Technical debt', 'Performance requirements', 'Scalability', 'Security'],
    tools: ['Code repository', 'CI/CD pipeline', 'Monitoring stack', 'Infra provisioner'],
    escalationRules: ['CEO approval for architectural overhauls', 'Product approval for scope changes'],
    communicationStyle: 'Precise, technical, iterative',
    activeTaskCount: 12,
    completedTasks: 211,
    successRate: 92,
    totalMessages: 412,
    resourceUsage: 91,
    color: '#3b82f6',
    gradient: 'from-blue-500/20 to-indigo-500/10',
  },
  {
    id: 'hr',
    name: 'HR',
    role: 'Human Resources',
    status: 'idle',
    hierarchyLevel: 2,
    trustLevel: 80,
    specialization: 'Talent acquisition, performance management, culture, compliance',
    autonomousActions: ['Screen candidates', 'Schedule interviews', 'Onboard employees', 'Run performance reviews'],
    decisionCriteria: ['Culture fit', 'Skill requirements', 'Budget constraints', 'Legal compliance'],
    tools: ['ATS system', 'HR database', 'Onboarding portal', 'Compliance checker'],
    escalationRules: ['CEO approval for executive hires', 'Legal review for terminations'],
    communicationStyle: 'Empathetic, structured, policy-aware',
    activeTaskCount: 2,
    completedTasks: 67,
    successRate: 89,
    totalMessages: 134,
    resourceUsage: 32,
    color: '#10b981',
    gradient: 'from-emerald-500/20 to-green-500/10',
  },
  {
    id: 'sales',
    name: 'Sales',
    role: 'Sales Manager',
    status: 'active',
    hierarchyLevel: 2,
    trustLevel: 82,
    specialization: 'Pipeline management, deal closing, revenue forecasting, customer relations',
    autonomousActions: ['Qualify leads', 'Send proposals', 'Negotiate contracts', 'Update CRM'],
    decisionCriteria: ['Deal size', 'Customer fit', 'Competitive landscape', 'Revenue potential'],
    tools: ['CRM system', 'Proposal generator', 'Revenue forecaster', 'Email sequencer'],
    escalationRules: ['CEO approval for deals >$100K', 'Finance review for custom pricing'],
    communicationStyle: 'Persuasive, relationship-focused, results-driven',
    activeTaskCount: 5,
    completedTasks: 89,
    successRate: 81,
    totalMessages: 298,
    resourceUsage: 55,
    color: '#22d3ee',
    gradient: 'from-cyan-500/20 to-teal-500/10',
  },
  {
    id: 'marketing',
    name: 'Marketing',
    role: 'Marketing Director',
    status: 'active',
    hierarchyLevel: 2,
    trustLevel: 79,
    specialization: 'Brand strategy, content creation, demand generation, market research',
    autonomousActions: ['Create content', 'Run campaigns', 'Analyze metrics', 'Manage social media'],
    decisionCriteria: ['Brand alignment', 'ROI', 'Audience reach', 'Competitor activity'],
    tools: ['Content studio', 'Campaign manager', 'Analytics platform', 'Social scheduler'],
    escalationRules: ['CEO approval for brand repositioning', 'Finance review for >$20K campaigns'],
    communicationStyle: 'Creative, data-informed, audience-centric',
    activeTaskCount: 6,
    completedTasks: 115,
    successRate: 83,
    totalMessages: 223,
    resourceUsage: 64,
    color: '#ec4899',
    gradient: 'from-pink-500/20 to-rose-500/10',
  },
  {
    id: 'finance',
    name: 'Finance',
    role: 'Chief Financial Officer',
    status: 'idle',
    hierarchyLevel: 1,
    trustLevel: 95,
    specialization: 'Budget management, financial forecasting, spend approval, compliance',
    autonomousActions: ['Approve spend <$10K', 'Generate financial reports', 'Manage payroll', 'Forecast runway'],
    decisionCriteria: ['ROI threshold (>=2.0x)', 'Budget availability', 'Regulatory compliance', 'Risk exposure'],
    tools: ['Budget tracker', 'Invoice manager', 'Financial modeler', 'Compliance auditor'],
    escalationRules: ['CEO approval for >$50K spend', 'Board notification for runway <6 months'],
    communicationStyle: 'Analytical, precise, conservative',
    activeTaskCount: 4,
    completedTasks: 178,
    successRate: 96,
    totalMessages: 167,
    resourceUsage: 41,
    color: '#f97316',
    gradient: 'from-orange-500/20 to-amber-500/10',
  },
]

export const AGENT_MAP = Object.fromEntries(AGENTS.map(a => [a.id, a])) as Record<string, Agent>

export const TASKS: Task[] = [
  { id: 't1', title: 'Define Q3 Product Roadmap', assignedTo: 'product', delegatedBy: 'ceo', status: 'in_progress', priority: 'high', dueDate: '2025-07-15', createdAt: '2025-06-20', description: 'Create comprehensive Q3 roadmap with feature priorities, resource requirements, and success metrics.', tags: ['roadmap', 'strategy'], progress: 65 },
  { id: 't2', title: 'Implement Auth Service v2', assignedTo: 'engineering', delegatedBy: 'product', status: 'in_progress', priority: 'critical', dueDate: '2025-07-08', createdAt: '2025-06-18', description: 'Rebuild authentication service with OAuth2, MFA support, and improved session management.', tags: ['auth', 'security', 'backend'], progress: 40 },
  { id: 't3', title: 'Launch SaaS Product Campaign', assignedTo: 'marketing', delegatedBy: 'ceo', status: 'in_progress', priority: 'high', dueDate: '2025-07-20', createdAt: '2025-06-22', description: 'Multi-channel campaign: LinkedIn, email sequences, blog posts, and paid ads targeting enterprise buyers.', tags: ['campaign', 'launch'], progress: 55 },
  { id: 't4', title: 'Q2 Budget Review & Reallocation', assignedTo: 'finance', delegatedBy: 'ceo', status: 'pending', priority: 'high', dueDate: '2025-07-01', createdAt: '2025-06-25', description: 'Review Q2 actuals vs forecast, identify variances, and propose reallocation for Q3.', tags: ['budget', 'finance'], progress: 0 },
  { id: 't5', title: 'Hire Senior Backend Engineers (x3)', assignedTo: 'hr', delegatedBy: 'ceo', status: 'in_progress', priority: 'high', dueDate: '2025-08-01', createdAt: '2025-06-10', description: 'Source, screen, and hire 3 senior backend engineers. Focus on distributed systems and Go expertise.', tags: ['hiring', 'engineering'], progress: 30 },
  { id: 't6', title: 'Enterprise Sales Outreach - Batch 4', assignedTo: 'sales', delegatedBy: 'product', status: 'blocked', priority: 'medium', dueDate: '2025-07-10', createdAt: '2025-06-28', description: 'Outreach to 50 enterprise prospects. Blocked pending updated sales deck from marketing.', tags: ['outreach', 'enterprise'], progress: 15, blockedReason: 'Waiting on updated sales deck from Marketing' },
  { id: 't7', title: 'Implement Real-Time Dashboard', assignedTo: 'engineering', delegatedBy: 'product', status: 'pending', priority: 'medium', dueDate: '2025-07-25', createdAt: '2025-06-29', description: 'Build WebSocket-based real-time dashboard with live KPI updates and agent status monitoring.', tags: ['frontend', 'realtime'], progress: 0 },
  { id: 't8', title: 'Competitor Analysis Report', assignedTo: 'marketing', delegatedBy: 'product', status: 'done', priority: 'medium', dueDate: '2025-06-30', createdAt: '2025-06-15', description: 'Comprehensive analysis of top 5 competitors: pricing, features, positioning, and weaknesses.', tags: ['research', 'competitive'], progress: 100 },
  { id: 't9', title: 'CEO Weekly Board Briefing', assignedTo: 'ceo', status: 'in_progress', priority: 'high', dueDate: '2025-07-05', createdAt: '2025-06-30', description: 'Prepare executive summary of weekly performance metrics, risks, and strategic decisions.', tags: ['reporting', 'executive'], progress: 20 },
  { id: 't10', title: 'Performance Review Cycle Q2', assignedTo: 'hr', status: 'pending', priority: 'medium', dueDate: '2025-07-15', createdAt: '2025-06-25', description: 'Coordinate Q2 performance reviews for all departments. Collect 360-degree feedback.', tags: ['performance', 'reviews'], progress: 0 },
]

export const MESSAGES: Message[] = [
  { id: 'msg-001', timestamp: '2025-07-01T09:14:32Z', sender: 'ceo', recipient: 'product', task_type: 'ROADMAP_REQUEST', context: { quarter: 'Q3', priority: 'revenue_growth' }, payload: { instruction: 'Prioritize features that increase ARPU by 15%', deadline: '2025-07-15', budget: 50000 }, status: 'done', delivery_state: 'done', urgency: 'high', computed_priority: 185, attempt_count: 1 },
  { id: 'msg-002', timestamp: '2025-07-01T09:22:11Z', sender: 'product', recipient: 'engineering', task_type: 'TASK_DELEGATION', context: { feature: 'auth-v2', spec: 'PRD-2025-041' }, payload: { task: 'Implement OAuth2 + MFA', estimate: '2 weeks', dependencies: ['auth-service', 'user-db'] }, status: 'in_progress', delivery_state: 'leased', urgency: 'critical', computed_priority: 210, attempt_count: 1 },
  { id: 'msg-003', timestamp: '2025-07-01T10:05:44Z', sender: 'ceo', recipient: 'finance', task_type: 'BUDGET_REVIEW', context: { period: 'Q2-2025' }, payload: { action: 'Review and reallocate remaining Q2 budget', target: 'engineering_capacity' }, status: 'pending', delivery_state: 'pending', urgency: 'high', computed_priority: 175, attempt_count: 0 },
  { id: 'msg-004', timestamp: '2025-07-01T10:31:07Z', sender: 'product', recipient: 'marketing', task_type: 'CAMPAIGN_BRIEF', context: { product: 'SaaS v2.0', segment: 'enterprise' }, payload: { goal: 'Generate 200 MQLs in Q3', channels: ['linkedin', 'email', 'content'], budget: 25000 }, status: 'in_progress', delivery_state: 'pending', urgency: 'normal', computed_priority: 130, attempt_count: 1 },
  { id: 'msg-005', timestamp: '2025-07-01T11:00:00Z', sender: 'marketing', recipient: 'sales', task_type: 'LEAD_HANDOFF', context: { batch: 'batch-4', quality: 'MQL' }, payload: { leads: 47, avgScore: 82, topSegment: 'fintech-enterprise' }, status: 'error', delivery_state: 'blocked', urgency: 'normal', computed_priority: 95, attempt_count: 3, error: 'Sales deck not updated - blocked by allowlist' },
  { id: 'msg-006', timestamp: '2025-07-01T11:15:22Z', sender: 'ceo', recipient: 'hr', task_type: 'HIRING_REQUEST', context: { department: 'engineering', urgency: 'q3_capacity' }, payload: { roles: ['Senior Backend Engineer x3'], budget: 420000, deadline: '2025-08-01' }, status: 'in_progress', delivery_state: 'leased', urgency: 'high', computed_priority: 160, attempt_count: 1 },
  { id: 'msg-007', timestamp: '2025-07-01T11:48:55Z', sender: 'finance', recipient: 'ceo', task_type: 'SPEND_APPROVAL', context: { type: 'infrastructure', vendor: 'AWS' }, payload: { amount: 85000, justification: 'Scale infra for Q3 growth', roi_projection: 2.4 }, status: 'pending', delivery_state: 'pending', urgency: 'high', computed_priority: 155, attempt_count: 0 },
  { id: 'msg-008', timestamp: '2025-07-01T12:00:00Z', sender: 'engineering', recipient: 'product', task_type: 'ESCALATION', context: { issue: 'scope_creep', sprint: 'sprint-14' }, payload: { issue: 'Auth v2 scope increased by 40%', options: ['reduce scope', 'extend timeline', 'add resources'], recommendation: 'reduce scope' }, status: 'pending', delivery_state: 'pending', urgency: 'high', computed_priority: 142, attempt_count: 0 },
]

export const WORKFLOWS: Workflow[] = [
  {
    id: 'wf-001',
    name: 'Launch SaaS MVP',
    status: 'active',
    goal: 'Ship v1 of SaaS product to first 50 enterprise customers',
    initiatedBy: 'ceo',
    currentStageIndex: 2,
    createdAt: '2025-06-01',
    updatedAt: '2025-07-01',
    tags: ['mvp', 'launch', 'saas'],
    progress: 40,
    stages: [
      { id: 's1', name: 'Ideation & Validation', assignedAgent: 'product', status: 'done', requiresApproval: false, dependencies: [], description: 'Market research, user interviews, problem validation' },
      { id: 's2', name: 'Planning & Architecture', assignedAgent: 'engineering', status: 'done', requiresApproval: true, dependencies: ['s1'], description: 'Technical design, resource planning, sprint breakdown' },
      { id: 's3', name: 'Core Development', assignedAgent: 'engineering', status: 'in_progress', requiresApproval: false, dependencies: ['s2'], description: 'Build auth, core features, API layer', duration: 336 },
      { id: 's4', name: 'Marketing Preparation', assignedAgent: 'marketing', status: 'in_progress', requiresApproval: false, dependencies: ['s2'], description: 'Landing page, launch content, email sequences' },
      { id: 's5', name: 'Sales Enablement', assignedAgent: 'sales', status: 'pending', requiresApproval: false, dependencies: ['s4'], description: 'Sales deck, demo environment, pricing strategy' },
      { id: 's6', name: 'CEO Approval & Launch', assignedAgent: 'ceo', status: 'pending', requiresApproval: true, dependencies: ['s3', 's4', 's5'], description: 'Executive review, go/no-go decision, public launch' },
      { id: 's7', name: 'Post-Launch Reporting', assignedAgent: 'finance', status: 'pending', requiresApproval: false, dependencies: ['s6'], description: 'Revenue tracking, CAC, LTV analysis, board report' },
    ],
  },
  {
    id: 'wf-002',
    name: 'Q3 Budget Reallocation',
    status: 'active',
    goal: 'Reallocate $200K from underperforming departments to engineering and sales',
    initiatedBy: 'finance',
    currentStageIndex: 1,
    createdAt: '2025-06-25',
    updatedAt: '2025-07-01',
    tags: ['budget', 'finance', 'q3'],
    progress: 25,
    stages: [
      { id: 's1', name: 'Financial Analysis', assignedAgent: 'finance', status: 'done', requiresApproval: false, dependencies: [], description: 'Analyze Q2 spend vs forecast, identify variances' },
      { id: 's2', name: 'Department Review', assignedAgent: 'finance', status: 'in_progress', requiresApproval: false, dependencies: ['s1'], description: 'Review each department budget request for Q3' },
      { id: 's3', name: 'CEO Approval', assignedAgent: 'ceo', status: 'pending', requiresApproval: true, dependencies: ['s2'], description: 'Executive sign-off on reallocation plan' },
      { id: 's4', name: 'Distribution', assignedAgent: 'finance', status: 'pending', requiresApproval: false, dependencies: ['s3'], description: 'Update budgets in financial system' },
    ],
  },
  {
    id: 'wf-003',
    name: 'Hire Virtual Support Team',
    status: 'active',
    goal: 'Hire 5 support staff to handle Q3 customer growth',
    initiatedBy: 'ceo',
    currentStageIndex: 1,
    createdAt: '2025-06-20',
    updatedAt: '2025-07-01',
    tags: ['hiring', 'hr', 'support'],
    progress: 20,
    stages: [
      { id: 's1', name: 'JD Creation', assignedAgent: 'hr', status: 'done', requiresApproval: false, dependencies: [], description: 'Write job descriptions for support roles' },
      { id: 's2', name: 'Sourcing & Screening', assignedAgent: 'hr', status: 'in_progress', requiresApproval: false, dependencies: ['s1'], description: 'Source candidates, run initial screens' },
      { id: 's3', name: 'Interview Loop', assignedAgent: 'hr', status: 'pending', requiresApproval: false, dependencies: ['s2'], description: 'Technical and culture interviews' },
      { id: 's4', name: 'Offer & Onboarding', assignedAgent: 'hr', status: 'pending', requiresApproval: true, dependencies: ['s3'], description: 'Extend offers, CEO approval for comp packages' },
    ],
  },
]

export const RESOURCES: Resource[] = [
  { id: 'r1', name: 'Engineering Capacity', category: 'capacity', ownedBy: 'engineering', total: 100, used: 91, unit: '%', forecastBurn: 98, warning: true, critical: false },
  { id: 'r2', name: 'Marketing Budget', category: 'budget', ownedBy: 'marketing', total: 150000, used: 98000, unit: '$', forecastBurn: 160000, warning: true, critical: false },
  { id: 'r3', name: 'Sales Quota', category: 'capacity', ownedBy: 'sales', total: 1000000, used: 420000, unit: '$', forecastBurn: 750000, warning: false },
  { id: 'r4', name: 'HR Hiring Budget', category: 'budget', ownedBy: 'hr', total: 500000, used: 85000, unit: '$', forecastBurn: 420000, warning: true },
  { id: 'r5', name: 'Compute (AWS)', category: 'compute', ownedBy: 'engineering', total: 50000, used: 32000, unit: '$/mo', forecastBurn: 55000, warning: true, critical: false },
  { id: 'r6', name: 'Total Company Budget', category: 'budget', ownedBy: 'finance', total: 2400000, used: 1140000, unit: '$', forecastBurn: 2200000, warning: false },
  { id: 'r7', name: 'Product Design Hours', category: 'time', ownedBy: 'product', total: 160, used: 124, unit: 'hrs', forecastBurn: 165, warning: true },
  { id: 'r8', name: 'CEO Time Allocation', category: 'time', ownedBy: 'ceo', total: 40, used: 18, unit: 'hrs/wk', warning: false },
]

export const BUDGET_ALLOCATIONS: BudgetAllocation[] = [
  { department: 'Engineering', agentId: 'engineering', allocated: 900000, spent: 512000, remaining: 388000 },
  { department: 'Marketing', agentId: 'marketing', allocated: 300000, spent: 196000, remaining: 104000, forecastedOverrun: 25000 },
  { department: 'Sales', agentId: 'sales', allocated: 450000, spent: 218000, remaining: 232000 },
  { department: 'HR', agentId: 'hr', allocated: 500000, spent: 85000, remaining: 415000 },
  { department: 'Product', agentId: 'product', allocated: 180000, spent: 92000, remaining: 88000 },
  { department: 'Finance', agentId: 'finance', allocated: 70000, spent: 37000, remaining: 33000 },
]

export const COMPANY_KPIS: KPIMetric[] = [
  { label: 'Task Completion Rate', value: '87%', delta: 4.2, trend: 'up', description: 'Tasks completed vs total' },
  { label: 'Avg Cycle Time', value: '3.4d', delta: -0.8, trend: 'up', description: 'Days from task creation to done' },
  { label: 'Revenue Forecast', value: '$2.4M', delta: 12, trend: 'up', description: 'Q3 projected ARR' },
  { label: 'Active Tasks', value: 39, delta: 5, trend: 'down', description: 'Tasks currently in progress' },
  { label: 'Blocked Tasks', value: 4, delta: 2, trend: 'down', description: 'Tasks waiting on dependencies' },
  { label: 'Total Messages', value: '1,879', delta: 18, trend: 'up', description: 'Inter-agent messages this week' },
]

export const ACTIVITY_FEED: ActivityEvent[] = [
  { id: 'e1', timestamp: '2025-07-01T12:05:00Z', agentId: 'engineering', type: 'escalation', title: 'Auth v2 scope escalated', description: 'Engineering escalated Auth v2 scope increase (40%) to Product for resolution', severity: 'warning' },
  { id: 'e2', timestamp: '2025-07-01T11:48:00Z', agentId: 'finance', type: 'approval', title: 'Spend approval requested', description: 'Finance submitted $85K AWS infrastructure spend for CEO approval', severity: 'info' },
  { id: 'e3', timestamp: '2025-07-01T11:15:00Z', agentId: 'ceo', type: 'message', title: 'Hiring order dispatched', description: 'CEO delegated hire of 3x Senior Backend Engineers to HR', severity: 'info' },
  { id: 'e4', timestamp: '2025-07-01T11:00:00Z', agentId: 'marketing', type: 'message', title: 'Lead handoff failed', description: 'Marketing→Sales lead handoff blocked: sales deck not updated', severity: 'error' },
  { id: 'e5', timestamp: '2025-07-01T10:31:00Z', agentId: 'product', type: 'workflow', title: 'Campaign brief sent', description: 'Product sent Q3 campaign brief to Marketing ($25K budget)', severity: 'info' },
  { id: 'e6', timestamp: '2025-07-01T10:05:00Z', agentId: 'ceo', type: 'task', title: 'Budget review initiated', description: 'CEO initiated Q2 budget review with Finance department', severity: 'info' },
  { id: 'e7', timestamp: '2025-07-01T09:22:00Z', agentId: 'product', type: 'task', title: 'Auth v2 delegated', description: 'Product delegated Auth v2 implementation to Engineering (critical priority)', severity: 'info' },
  { id: 'e8', timestamp: '2025-07-01T09:14:00Z', agentId: 'ceo', type: 'simulation', title: 'Q3 roadmap requested', description: 'CEO requested Q3 product roadmap from Product Manager', severity: 'info' },
]

export const ALERTS: Alert[] = [
  { id: 'a1', timestamp: '2025-07-01T12:05:00Z', severity: 'warning', title: 'Engineering at 91% capacity', description: 'Engineering department is near capacity. 3 new tasks queued. Risk of delays to Q3 milestones.', agentId: 'engineering', resolved: false, actionRequired: 'Approve hiring or reduce task scope' },
  { id: 'a2', timestamp: '2025-07-01T11:00:00Z', severity: 'error', title: 'Sales lead handoff blocked', description: 'Marketing → Sales message dead-lettered after 3 attempts. Missing updated sales deck.', agentId: 'sales', resolved: false, actionRequired: 'Marketing must update sales deck' },
  { id: 'a3', timestamp: '2025-07-01T10:00:00Z', severity: 'warning', title: 'Marketing budget overrun risk', description: 'Marketing forecasted to spend $160K against $150K allocation. $10K overrun projected.', agentId: 'marketing', resolved: false, actionRequired: 'Approve budget increase or reduce Q3 campaign scope' },
  { id: 'a4', timestamp: '2025-07-01T09:00:00Z', severity: 'info', title: 'AWS spend approval pending', description: '$85K infrastructure spend awaiting CEO approval. Unblocks Q3 scaling plan.', agentId: 'finance', resolved: false, actionRequired: 'CEO approval required' },
]

export const SIMULATIONS: Simulation[] = [
  {
    id: 'sim-001',
    name: 'Launch SaaS Product',
    goal: 'Simulate full go-to-market launch of SaaS v2.0 targeting enterprise fintech',
    status: 'running',
    mode: 'multi',
    participatingAgents: ['ceo', 'product', 'engineering', 'marketing', 'sales', 'finance'],
    startedAt: '2025-07-01T08:00:00Z',
    budget: 500000,
    timeHorizon: 'Q3 2025',
    targetCustomer: 'Enterprise fintech (100-500 employees)',
    progress: 38,
    events: [
      { id: 'se1', timestamp: '2025-07-01T08:05:00Z', agentId: 'ceo', action: 'Set quarterly goal', decision: 'Increase ARR by 15% through SaaS launch', impact: 'All agents aligned on revenue target' },
      { id: 'se2', timestamp: '2025-07-01T08:12:00Z', agentId: 'product', action: 'Backlog prioritization', decision: 'Auth + core features first, polish later', impact: 'Engineering unblocked on critical path' },
      { id: 'se3', timestamp: '2025-07-01T08:25:00Z', agentId: 'finance', action: 'Budget review', decision: 'Approved $85K AWS spend (ROI 2.4x)', impact: 'Infrastructure scaling approved' },
      { id: 'se4', timestamp: '2025-07-01T09:00:00Z', agentId: 'marketing', action: 'Campaign launch', decision: 'LinkedIn + email targeting 200 MQLs', impact: 'Demand generation pipeline activated' },
    ],
  },
  {
    id: 'sim-002',
    name: 'Revenue Increase 15%',
    goal: 'Model strategies to increase quarterly revenue by 15%',
    status: 'paused',
    mode: 'single',
    participatingAgents: ['ceo'],
    startedAt: '2025-06-28T14:00:00Z',
    budget: 100000,
    timeHorizon: 'Q3-Q4 2025',
    progress: 60,
    events: [],
  },
]

export const APPROVAL_REQUESTS: ApprovalRequest[] = [
  { id: 'apr-001', requestedBy: 'finance', type: 'SPEND', title: 'AWS Infrastructure Expansion', description: 'Scale AWS infrastructure to handle Q3 growth. 3x current capacity needed.', amount: 85000, status: 'pending', createdAt: '2025-07-01T11:48:00Z' },
  { id: 'apr-002', requestedBy: 'marketing', type: 'BUDGET', title: 'Q3 Campaign Budget Increase', description: 'Marketing forecasts $10K overrun on Q3 campaigns. Request reallocation from HR underspend.', amount: 10000, status: 'pending', createdAt: '2025-07-01T10:00:00Z' },
  { id: 'apr-003', requestedBy: 'hr', type: 'HIRING', title: 'Offer Package - Senior Backend #1', description: 'Approve compensation package for first senior backend engineer hire.', amount: 145000, status: 'pending', createdAt: '2025-07-01T09:30:00Z' },
  { id: 'apr-004', requestedBy: 'product', type: 'SCOPE', title: 'Auth v2 Timeline Extension', description: 'Request 1-week extension on Auth v2 deadline due to scope increase from Engineering.', status: 'pending', createdAt: '2025-07-01T08:45:00Z' },
]

// Chart data for resource utilization over time
export const RESOURCE_OVER_TIME = [
  { week: 'W1', engineering: 72, marketing: 58, sales: 45, hr: 28, product: 61, finance: 35 },
  { week: 'W2', engineering: 78, marketing: 64, sales: 49, hr: 31, product: 68, finance: 38 },
  { week: 'W3', engineering: 85, marketing: 71, sales: 53, hr: 30, product: 74, finance: 40 },
  { week: 'W4', engineering: 91, marketing: 65, sales: 55, hr: 32, product: 78, finance: 41 },
]

export const TASK_THROUGHPUT = [
  { day: 'Mon', created: 8, completed: 5, blocked: 2 },
  { day: 'Tue', created: 12, completed: 9, blocked: 1 },
  { day: 'Wed', created: 6, completed: 11, blocked: 3 },
  { day: 'Thu', created: 9, completed: 7, blocked: 2 },
  { day: 'Fri', created: 14, completed: 10, blocked: 1 },
  { day: 'Sat', created: 3, completed: 6, blocked: 0 },
  { day: 'Sun', created: 2, completed: 4, blocked: 0 },
]

export const REVENUE_FORECAST = [
  { month: 'Jan', actual: 180000, forecast: 175000 },
  { month: 'Feb', actual: 195000, forecast: 190000 },
  { month: 'Mar', actual: 210000, forecast: 205000 },
  { month: 'Apr', actual: 228000, forecast: 220000 },
  { month: 'May', actual: 245000, forecast: 235000 },
  { month: 'Jun', actual: 262000, forecast: 255000 },
  { month: 'Jul', forecast: 285000 },
  { month: 'Aug', forecast: 310000 },
  { month: 'Sep', forecast: 340000 },
]

export const AGENT_LOAD: AgentLoad[] = [
  { name: 'Engineering', agentId: 'engineering', value: 91, color: 'var(--agent-engineering)' },
  { name: 'Product',     agentId: 'product',     value: 78, color: 'var(--agent-product)' },
  { name: 'Marketing',   agentId: 'marketing',   value: 64, color: 'var(--agent-marketing)' },
  { name: 'Sales',       agentId: 'sales',       value: 55, color: 'var(--agent-sales)' },
  { name: 'CEO',         agentId: 'ceo',         value: 45, color: 'var(--agent-ceo)' },
  { name: 'Finance',     agentId: 'finance',     value: 41, color: 'var(--agent-finance)' },
  { name: 'HR',          agentId: 'hr',          value: 32, color: 'var(--agent-hr)' },
]

export const PIPELINE: PipelineStage[] = [
  { stage: 'Prospect',    count: 142, value: 0,    color: 'var(--text-3)' },
  { stage: 'Qualified',   count: 86,  value: 1240, color: 'var(--sky)' },
  { stage: 'Proposal',    count: 34,  value: 980,  color: 'var(--indigo)' },
  { stage: 'Negotiation', count: 18,  value: 720,  color: 'var(--amber)' },
  { stage: 'Closed Won',  count: 11,  value: 480,  color: 'var(--green)' },
]

export const MESSAGE_FLOW: MessageFlow[] = [
  { from: 'ceo',         to: 'product',     count: 42 },
  { from: 'ceo',         to: 'finance',     count: 38 },
  { from: 'ceo',         to: 'hr',          count: 21 },
  { from: 'product',     to: 'engineering', count: 89 },
  { from: 'product',     to: 'marketing',   count: 47 },
  { from: 'marketing',   to: 'sales',       count: 64 },
  { from: 'engineering', to: 'product',     count: 38 },
  { from: 'finance',     to: 'ceo',         count: 27 },
  { from: 'sales',       to: 'finance',     count: 31 },
]

export const KANOSEI_WORKFLOWS: KanoseiWorkflow[] = [
  {
    id: 'wf1', name: 'Launch SaaS MVP', progress: 40, status: 'active', owner: 'ceo',
    stages: [
      { name: 'Validation',     agent: 'product',     status: 'done' },
      { name: 'Architecture',   agent: 'engineering', status: 'done' },
      { name: 'Core Build',     agent: 'engineering', status: 'active' },
      { name: 'Marketing Prep', agent: 'marketing',   status: 'active' },
      { name: 'Sales Enable',   agent: 'sales',       status: 'pending' },
      { name: 'Launch',         agent: 'ceo',         status: 'pending' },
    ],
  },
  {
    id: 'wf2', name: 'Q3 Budget Reallocation', progress: 25, status: 'active', owner: 'finance',
    stages: [
      { name: 'Analysis',     agent: 'finance', status: 'done' },
      { name: 'Dept Review',  agent: 'finance', status: 'active' },
      { name: 'CEO Approval', agent: 'ceo',     status: 'pending' },
      { name: 'Distribute',   agent: 'finance', status: 'pending' },
    ],
  },
  {
    id: 'wf3', name: 'Hire Senior Backend Team', progress: 30, status: 'active', owner: 'hr',
    stages: [
      { name: 'JD Creation',     agent: 'hr', status: 'done' },
      { name: 'Source & Screen', agent: 'hr', status: 'active' },
      { name: 'Interviews',      agent: 'hr', status: 'pending' },
      { name: 'Offer & Onboard', agent: 'hr', status: 'pending' },
    ],
  },
]

export const NOTIFICATIONS: KanoseiNotification[] = [
  { id: 'n1', section: 'Engineering', sectionPath: 'agents', severity: 'warning', title: 'Engineering at 91% capacity', desc: 'Kano flagged 3 queued tasks. Risk of Q3 delays.', when: '2m', unread: true, agentId: 'engineering' },
  { id: 'n2', section: 'Finance',     sectionPath: 'overview', severity: 'pending', title: 'AWS spend $85K awaiting approval', desc: 'Finance agent submitted infrastructure scaling spend.', when: '8m', unread: true, agentId: 'finance' },
  { id: 'n3', section: 'Sales',       sectionPath: 'workflows', severity: 'error',  title: 'Lead handoff failed (3 attempts)', desc: 'Marketing → Sales blocked — sales deck not updated.', when: '14m', unread: true, agentId: 'sales' },
  { id: 'n4', section: 'Marketing',   sectionPath: 'overview', severity: 'warning', title: 'Marketing budget overrun projected', desc: '$10K projected variance. Reallocate or scope down?', when: '32m', unread: false, agentId: 'marketing' },
  { id: 'n5', section: 'HR',          sectionPath: 'workflows', severity: 'info',   title: 'HR completed candidate screen', desc: '12 candidates scored — top 3 ready for review.', when: '1h', unread: false, agentId: 'hr' },
  { id: 'n6', section: 'Product',     sectionPath: 'overview', severity: 'info',    title: 'Product shipped Q3 roadmap draft', desc: '6 themes, 14 initiatives. Awaiting your review.', when: '3h', unread: false, agentId: 'product' },
]
