"""Bootstrap router agents and write local env helper files.

This is a convenience wrapper around the router admin API. It registers the
default agents, issues fresh API keys, and writes:

  .router_keys.ps1              PowerShell env setup for agent workers
  .router_keys.cmd              Command Prompt env setup for agent workers
  website/.env.local.generated  Next.js env values for the website

Use --write-website-env to write website/.env.local directly.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Any

import requests  # pyright: ignore[reportMissingModuleSource]

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.bootstrap_router_agents import AGENTS, RUNNER_ENV_NAMES, WEBSITE_ENV_NAMES

DEFAULT_BASE_URL = "http://localhost:8000"
DEFAULT_ADMIN_SECRET = "dev-admin-secret"


def assert_router_available(base_url: str) -> None:
    try:
        response = requests.get(f"{base_url.rstrip('/')}/health", timeout=5)
        response.raise_for_status()
    except requests.RequestException as exc:
        raise SystemExit(
            "Enterprise Router is not reachable. Start it first, then rerun setup.\n"
            f"Expected router URL: {base_url.rstrip('/')}\n"
            "PowerShell:\n"
            '  $env:ENTERPRISE_ROUTER_BACKEND="sqlite"\n'
            '  $env:ENTERPRISE_ROUTER_DB="enterprise_router_demo.db"\n'
            '  $env:ENTERPRISE_ROUTER_ADMIN_SECRET="dev-admin-secret"\n'
            '  $env:ENTERPRISE_ROUTER_PORT="8000"\n'
            "  python -m enterprise_router.api"
        ) from exc


def register_agent(
    *,
    base_url: str,
    admin_secret: str,
    name: str,
    role: str,
    hierarchy: int,
    trust: int,
    allowed_task_types: list[str],
) -> str:
    response = requests.post(
        f"{base_url.rstrip('/')}/agents",
        headers={"X-Admin-Secret": admin_secret, "Content-Type": "application/json"},
        json={
            "agent_name": name,
            "role": role,
            "hierarchy_level": hierarchy,
            "trust_level": trust,
            "allowed_task_types": allowed_task_types,
            "issue_api_key": True,
        },
        timeout=10,
    )
    response.raise_for_status()
    data = response.json()
    if not isinstance(data, dict):
        raise ValueError(f"Expected object response while registering {name}.")
    key = data.get("api_key")
    if not isinstance(key, str) or not key:
        raise ValueError(f"Router did not issue an API key for {name}.")
    return key


def ps_quote(value: str) -> str:
    return value.replace("`", "``").replace('"', '`"')


def cmd_quote(value: str) -> str:
    return value.replace('"', '""')


def write_text(path: Path, content: str, *, dry_run: bool) -> None:
    if dry_run:
        print(f"[dry-run] would write {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"Wrote {path}")


def build_runner_ps1(base_url: str, issued_keys: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/setup_local_runtime.py",
        "# Dot-source this file in PowerShell: . .\\.router_keys.ps1",
        f'$env:ENTERPRISE_ROUTER_URL="{ps_quote(base_url)}"',
    ]
    for name, key in issued_keys.items():
        env_name = RUNNER_ENV_NAMES.get(name)
        if env_name:
            lines.append(f'$env:{env_name}="{ps_quote(key)}"')
    lines.append("")
    return "\n".join(lines)


def build_runner_cmd(base_url: str, issued_keys: dict[str, str]) -> str:
    lines = [
        "@echo off",
        "REM Generated by scripts/setup_local_runtime.py",
        "REM Use in cmd.exe: call .router_keys.cmd",
        f'set "ENTERPRISE_ROUTER_URL={cmd_quote(base_url)}"',
    ]
    for name, key in issued_keys.items():
        env_name = RUNNER_ENV_NAMES.get(name)
        if env_name:
            lines.append(f'set "{env_name}={cmd_quote(key)}"')
    lines.append("")
    return "\n".join(lines)


def build_website_env(base_url: str, admin_secret: str, issued_keys: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/setup_local_runtime.py",
        f"NEXT_PUBLIC_API_URL={base_url}",
        f"NEXT_PUBLIC_ADMIN_SECRET={admin_secret}",
    ]
    for name, key in issued_keys.items():
        env_name = WEBSITE_ENV_NAMES.get(name)
        if env_name:
            lines.append(f"{env_name}={key}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Register router agents and write local env setup files."
    )
    parser.add_argument(
        "--base-url",
        default=os.getenv("ENTERPRISE_ROUTER_URL", os.getenv("ENTERPRISE_ROUTER_API_URL", DEFAULT_BASE_URL)),
    )
    parser.add_argument(
        "--admin-secret",
        default=os.getenv("ENTERPRISE_ROUTER_ADMIN_SECRET", DEFAULT_ADMIN_SECRET),
    )
    parser.add_argument("--runtime-ps1", default=str(ROOT / ".router_keys.ps1"))
    parser.add_argument("--runtime-cmd", default=str(ROOT / ".router_keys.cmd"))
    parser.add_argument("--website-env-generated", default=str(ROOT / "website" / ".env.local.generated"))
    parser.add_argument(
        "--write-website-env",
        action="store_true",
        help="Write website/.env.local directly instead of only .env.local.generated.",
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    base_url = str(args.base_url).rstrip("/")
    issued_keys: dict[str, str] = {}
    if args.dry_run:
        issued_keys = {name: f"<{RUNNER_ENV_NAMES.get(name, name + '_API_KEY')}>" for name, *_ in AGENTS}
        for name, *_ in AGENTS:
            print(f"[dry-run] would register {name}")
    else:
        assert_router_available(base_url)
        for name, role, hierarchy, trust, allowed_task_types in AGENTS:
            key = register_agent(
                base_url=base_url,
                admin_secret=args.admin_secret,
                name=name,
                role=role,
                hierarchy=hierarchy,
                trust=trust,
                allowed_task_types=allowed_task_types,
            )
            issued_keys[name] = key
            print(f"{name}: registered")

    write_text(Path(args.runtime_ps1), build_runner_ps1(base_url, issued_keys), dry_run=args.dry_run)
    write_text(Path(args.runtime_cmd), build_runner_cmd(base_url, issued_keys), dry_run=args.dry_run)
    write_text(
        Path(args.website_env_generated),
        build_website_env(base_url, args.admin_secret, issued_keys),
        dry_run=args.dry_run,
    )

    if args.write_website_env:
        write_text(
            ROOT / "website" / ".env.local",
            build_website_env(base_url, args.admin_secret, issued_keys),
            dry_run=args.dry_run,
        )
    else:
        print("Website env was written to website/.env.local.generated.")
        print("Run with --write-website-env to update website/.env.local automatically.")

    print("\nNext:")
    print("  PowerShell: . .\\.router_keys.ps1")
    print("  Then:       python .\\run_agents.py --agents all")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
